# Generated by Django 2.2 on 2019-04-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.BooleanField()),
            ],
        ),
    ]
