# Generated by Django 2.2 on 2019-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190412_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
