# Generated by Django 2.2 on 2019-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testtable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='date',
            field=models.DateField(default=None, verbose_name='YYYY:MM:DD'),
        ),
    ]
