# Generated by Django 2.2 on 2019-04-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190413_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
