# Generated by Django 2.2 on 2019-04-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
